### ISSUE TITLE
Re-add home intro with timestamp

### ISSUE THREAD

**Issue by peduarte** [fathomlondon/fathomlondon.com#140]
The initial home intro was taking too long, so we've been asked to remove it. I proposed an idea to Ant which was to only show the animation once per user in a given time frame. He likes that - but I'm still not 100% convinced.

The way it'd work is: the first time a user lands on the website, we show the long home intro and we store a value in Local Storage with a timestamp. Any future visits to the website, we check how old the timestamp is. If it's older than **N** days we show the home intro again, otherwise, we bypass it. 

We still need to define **N**.

For reference here's a link to the PR which removed the home intro: https://github.com/fathomlondon/fathomlondon.github.io/pull/139

**Comment by ibrennan** [comment]
@peduarte status on this? It looks to me good how it is now, the animation is quick and mostly non-blocking

**Comment by peduarte** [comment]
I think everyone's happy with how it currently is:

A simple fade in animation on all pages.

So to clarify, the long intro animation has been removed with no plans to be added back.
