### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by ibrennan** [fathomlondon/fathomlondon.com#171]
We have moved away from github.io for hosting, and now use Netlify.

Propose renaming this repo to just Fathomlondon

**Comment by AndrewJDick** [comment]
@ibrennan 

@peduarte says no

Can we keep the name as is, and delete this instead: 
https://github.com/fathomlondon/fathom-website

**Comment by ibrennan** [comment]
@AndrewJDick this has already been done, at the time of writing the repo was called fathomlondon.github.io. 

Closing the issue because @peduarte already did it, even though he says no 🤷‍♂️
