### ISSUE TITLE
Migrate Blog posts

### ISSUE THREAD

**Issue by AndrewJDick** [fathomlondon/fathomlondon.com#183]

**Comment by peduarte** [comment]
@AndrewJDick @jfidiles 

I’ve created an the initial `gatsby-node` setup to allow us to dynamically create `html` pages from `md` files

I also create a `post` template, which will be used to render the blog posts.

I’m already querying and passing through a  bit of data as an example, but can one of you pick up the task and finalize the styling of the Blog Post page?

Here’s the PR https://github.com/fathomlondon/fathomlondon.com/pull/207
And here’s the a blog page: https://deploy-preview-207--fathomlondon.netlify.com/2017/12/21/eight-key-fintech-trends-to-watch-in-2018.html

Note: I’ve had to create a custom slug based off the file name, this is to ensure the URLs are compatible with our current site.

Any questions please let me know
