### ISSUE TITLE
Migrate global components

### ISSUE THREAD

**Issue by peduarte** [fathomlondon/fathomlondon.com#193]
Mainly `Nav` and `Footer` (and any other components they depend on)

**Comment by artisologic** [comment]
@peduarte is this basically creating the Layout? I can't see a task for that so assuming it's this one.
Probably should be the first thing to tackle?

**Comment by peduarte** [comment]
The layout has been created here https://github.com/fathomlondon/fathomlondon.com/pull/191 but that only adds global styles to it.

This issue will add Nav, Footer and few other components that the pages depend on.

@jfidiles has already made a start on this - once he's done he'll do #185 👍
