### ISSUE TITLE
Text formatting issues (from Will)

### ISSUE THREAD

**Issue by peduarte** [fathomlondon/fathomlondon.com#196]
- under the first quote (‘When digital transformation is done right…’) - the credit (starting with ‘George…’) needs to be clearly different, perhaps bold and smaller?
- the definition (‘Digital transformation is the overall effect…‘)  is split across two paragraphs, one of which is blockquote style and one is body style, can we have them both as just one style?
- the definition then goes onto be unpacked, with those superscript numbers referred to in a numbered list… can this be an `<ol>`?
- the paragraph that begins ‘* machine learning’ is meant to be a bulleted list
- in the ‘Culture’ section we have a quote by Peter Drucker, this should be formatted the same as that opening quote by George Westerman

**Comment by AndrewJDick** [comment]
Can any of these changes be implemented via the CMS?

**Comment by AndrewJDick** [comment]
> under the first quote (‘When digital transformation is done right…’) - the credit (starting with ‘George…’) needs to be clearly different, perhaps bold and smaller?

![image](https://user-images.githubusercontent.com/12872535/46482178-fddb0a00-c7ec-11e8-8f3f-13c8e0bfedac.png)

**Comment by AndrewJDick** [comment]
in the ‘Culture’ section we have a quote by Peter Drucker, this should be formatted the same as that opening quote by George Westerman

![image](https://user-images.githubusercontent.com/12872535/46483040-ab025200-c7ee-11e8-8fe3-7533c01901c8.png)

`===`

**Comment by AndrewJDick** [comment]
> the definition (‘Digital transformation is the overall effect…‘) is split across two paragraphs, one of which is blockquote style and one is body style, can we have them both as just one style?

Both are now blockquote style

**Comment by AndrewJDick** [comment]
> the definition then goes onto be unpacked, with those superscript numbers referred to in a numbered list… can this be an <ol>?

![image](https://user-images.githubusercontent.com/12872535/46484102-fe759f80-c7f0-11e8-808b-007d79f93ebb.png)

**Comment by AndrewJDick** [comment]
> the paragraph that begins ‘* machine learning’ is meant to be a bulleted list

![image](https://user-images.githubusercontent.com/12872535/46484160-19481400-c7f1-11e8-830f-65b000b34514.png)

**Comment by AndrewJDick** [comment]
@vandallondon can you give this a once over and close it out if you're happy with it. 

If there's something you want to tweak, all the changes were performed via the cms 👍

**Comment by AndrewJDick** [comment]
Changes implemented. Closing out. 

If anything has been missed, I'll open it as a separate issue.
