### ISSUE TITLE
Scripting error when returning to the homepage

### ISSUE THREAD

**Issue by artisologic** [fathomlondon/fathomlondon.com#244]
Just discovered this randomly when clicking around.

Steps to reproduce:

- load fathomlondon.com
- navigate to another page than the homepage
- try to go back to the homepage

![image](https://user-images.githubusercontent.com/1539897/36355759-02de52a2-14e0-11e8-9ac8-70424ef94506.png)

**Comment by peduarte** [comment]
Tracing this issue https://github.com/gatsbyjs/gatsby/issues/4115
