### ISSUE TITLE
Add Privacy Policy and Cooky Policy Pages

### ISSUE THREAD

**Issue by peduarte** [fathomlondon/fathomlondon.com#298]
We need to add those two new pages as well as links to them from the footer.

Copy to be provide by Preete.

**Comment by alexjfathom** [comment]
@peduarte do we have designs/copy for this yet?

**Comment by peduarte** [comment]
@alexjfathom there are no designs, we'll use the same style as we do for the Article Page, but without the big header image. If you start on this let me know and I can help out with the design.
