### ISSUE TITLE
Fathom New York

### ISSUE THREAD

**Issue by ibrennan** [fathomlondon/fathomlondon.com#314]
Acceptance criteria:

- Domain name `fathom-newyork.com` has been registered, need a version of the site on that domain that shows the correct address details.
- Details to be changed captured in the following screenshots:
<img width="951" alt="screen shot 2018-07-27 at 15 51 52" src="https://user-images.githubusercontent.com/1170905/43328068-0285542a-91b5-11e8-9a6c-c7c0bafc290f.png">
<img width="1184" alt="screen shot 2018-07-27 at 15 51 48" src="https://user-images.githubusercontent.com/1170905/43328070-029b0892-91b5-11e8-8f66-4dc3475d96e2.png">
<img width="1222" alt="screen shot 2018-07-27 at 15 51 28" src="https://user-images.githubusercontent.com/1170905/43328071-02b16dd0-91b5-11e8-94ba-a920fe101915.png">
<img width="886" alt="screen shot 2018-07-27 at 15 51 16" src="https://user-images.githubusercontent.com/1170905/43328072-02c8ed7a-91b5-11e8-93b1-c4c88ec59c9d.png">

This is designed to be a quick win solution, we need to think of a better global branding piece to handle website, social profiles, and copy across media.

**Comment by ibrennan** [comment]
Is this something we should fork this repo and produce as a quick win? Once a more stable and scalable approach is thought out, we can migrate back. Alternatively can we do this with the CMS already?

**Comment by artisologic** [comment]
@ibrennan does it have to be 2 different websites? why can't we put 2 addresses?

**Comment by peduarte** [comment]
We could fork the whole repo and agree that would be the quickest win. If we did that, it would come with the CMS included. We’d then have to update the careers page and the copy where required. I wouldn’t make the copy CMS-able though. 

But I also agree with Benoît, why can’t it be the same website? 

Another thing we could do is run 2 different builds with different flags, and do the text replacement that way then deploy the builds to different environments. Not sure Netlify supports that with one repo though.

**Comment by matthewfowles** [comment]
If we want this out in the next few weeks I feel we fork temporarily. In the longer term we should have one site that encompasses all three. @peduarte What is the process for design and content management on this?

**Comment by matthewfowles** [comment]
Ok @ibrennan I can do today. Is it all cool to contact Will about copy???

**Comment by matthewfowles** [comment]
Actually it's one screen, I can swap it out :)
