### ISSUE TITLE
New York - OG tags + Privacy Policy still reference london

### ISSUE THREAD

**Issue by ibrennan** [fathomlondon/fathomlondon.com#320]
http://fathom-newyork.com/privacy-policy/

<img width="820" alt="screen shot 2018-08-03 at 12 26 33" src="https://user-images.githubusercontent.com/1170905/43640658-9f3230d2-9718-11e8-8215-3f2740a87b9d.png">

**Comment by AndrewJDick** [comment]
PR in on the NY repo: 
https://github.com/fathomlondon/fathom-newyork.com/pull/2

**Comment by AndrewJDick** [comment]
Merged in. Closing out
