### ISSUE TITLE
Change content and design to be global branded

### ISSUE THREAD

**Issue by ibrennan** [fathomlondon/fathomlondon.com#431]
Because of #430 we need to do the following:

- [x] All website copy should be in English (UK) as apposed to English (US), our global HQ is London so the site copy should reflect that 🇬🇧
- [x] Update contact page to show both office details 
- [x] Update home page to show both office details
- [x] Remove the mention of `Fathom London` or `Fathom New York`, instead the name should always be `Fathom`
- [x] Update careers page to show toggle between locations: https://github.com/fathomlondon/fathomlondon.com/pull/435

**Comment by jjenzz** [comment]
> Remove the mention of Fathom London or Fathom New York, instead the name should always be Fathom

@ibrennan Does this include references to "Fathom London Limited" in the terms and privacy pages?

**Comment by ibrennan** [comment]
@jjenzz good point, legal entity name should remain as is on the terms and privacy pages.
